{{- if and .Values.frontend.enabled .Values.frontend.httpRoute.enabled }}
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: {{ include "controlplane.frontend.fullname" . }}
  labels:
    {{- include "controlplane.frontend.labels" . | nindent 4 }}
  {{- with .Values.frontend.httpRoute.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  parentRefs:
    {{- toYaml .Values.frontend.httpRoute.parentRefs | nindent 4 }}
  {{- if .Values.frontend.httpRoute.hostnames }}
  hostnames:
    {{- toYaml .Values.frontend.httpRoute.hostnames | nindent 4 }}
  {{- end }}
  rules:
    {{- range .Values.frontend.httpRoute.rules }}
    - matches:
        {{- toYaml .matches | nindent 8 }}
      backendRefs:
        - name: {{ include "controlplane.frontend.fullname" $ }}
          port: {{ $.Values.frontend.service.port }}
    {{- end }}
{{- end }}

