{{- if .Values.database.url }}
{{- if not .Values.database.existingSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "controlplane.fullname" . }}-db
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
type: Opaque
stringData:
  database-url: {{ .Values.database.url | quote }}
  {{- if and .Values.migrations.enabled .Values.migrations.password }}
  password: {{ .Values.migrations.password | quote }}
  {{- end }}
{{- end }}
{{- end }}
