apiVersion: v1
kind: Service
metadata:
  name: {{ include "controlplane.fullname" . }}
  labels:
    {{- include "controlplane.labels" . | nindent 4 }}
spec:
  type: {{ .Values.controlplane.service.type }}
  ports:
    - port: {{ .Values.controlplane.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "controlplane.selectorLabels" . | nindent 4 }}
